---
- name: Solving test environment
  hosts: all
  become: False
  gather_facts: False
  vars:
  - filename: "test.txt"
  tasks:
  - name: Create a file
    file: 
      path: "{{ filename }}"
      state: present
