---
- name: Creating project and job templates in AWX
  hosts: localhost
  connection: local
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  vars:
    pb_names: 
    - 'deploy'
    - 'solve'
    - 'verify'
  tasks:
  - name: Create project
    awx.awx.project:
      name: "{{ project_name }}"
      description: "{{ project_description }}"
      organization: "Default"
      controller_config_file: "{{ controller_config_file }}"
      scm_type: "git"
      scm_url: "{{ scm_url }}"
      scm_branch: "{{ scm_branch }}"
      scm_update_on_launch: True
      scm_update_cache_timeout: 30
      state: "present"
  - name: Create job templates
    awx.awx.job_template:
      name: "{{ project_name }}: {{ item }}"
      project: "{{ project_name }}"
      controller_config_file: "{{ controller_config_file }}"
      job_type: "run"
      inventory: "LXD"
      ask_limit_on_launch: True
      playbook: "{{ item }}.yml"
      credentials: ["OLSAP"]
      state: "present"
    loop: "{{ pb_names }}"
