---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "Please create a named pipe with the following path: {{ filename }}"
  - name: "Deleting a file {{ filename }}"
    file: 
      path: "{{ filename }}"
      state: "absent"

