---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Create directory
    debug: 
      msg: "Please create {{ directory }} directory"
