---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset: ['!all','!min','os_family']
  vars_files:
  - vars.yml
  tasks:
#  - debug: 
#      var: ansible_facts
  - debug: 
      msg: "Uninstalling the package '{{ package }}'"
  - name: Uninstalling the package
    apt:
      name: "{{ package }}"
      state: absent
    when: ansible_facts['os_family'] == "Debian"
