---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "{{ project_description }}"
  - name: "Deleting artefacts"
    file: 
      path: "{{ item }}"
      state: "absent"
    loop:
    - "{{ workdir }}{{ directory }}"
    - "{{ workdir }}/{{ archive }}"
    - "{{ workdir }}/{{ filename }}"
  - name: "Compress directory {{ directory }} into {{ archive }}"
    archive:
      path: "{{ directory }}"
      dest: "{{ workdir }}/{{ archive }}"
