---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "Please create a symbolic link to {{ source }}/{{ filename }} in {{ destination }}"
  - name: "Deleting a file {{ destination }}/{{ filename }}"
    file: 
      path: "{{ destination }}/{{ filename }}"
      state: "absent"

