---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "{{ project_description }}"
  - name: "Deleting the files"
    file: 
      path: "{{ item }}"
      state: "absent"
    with_items:
    - "{{ filename }}"
