---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "Please create {{ filename }} and set immutable attribute"
  - name: Unsetting the attribute
    file:
      path: "{{ filename }}"
      attributes: "-i"
      state: touch
    ignore_errors: True
  - name: Removing the file "{{ filename }}"
    file:
      path: "{{ filename }}"
      state: absent
