---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_name }}"
    debug: 
      msg: "Please create {{ directory }} directory"
  - name: "Deleting directory {{ parent_directory }}"
    file: 
      path: "{{ parent_directory }}"
      state: absent
