---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "{{ project_description }}"
    debug: 
      msg: "Please store system UUID in a {{ filename }}"
  - name: Removing the file
    file: 
      path: "{{ filename }}"
      state: "absent"
