---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: True
  gather_subset: ['!all','!min','os_family']
  vars_files:
  - vars.yml
  tasks:
#  - debug: 
#      var: ansible_facts
#  - debug: 
#      msg: "Uninstalling the package '{{ package }}'"
  - name: "Uninstalling the package '{{ package }}'"
    apt:
      name: "{{ package }}"
      state: "absent"
    when: ansible_facts['os_family'] == "Debian"
