---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Fetching system UUID
    debug: 
      msg: "Please store system UUID in a {{ filename }}"
