---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Creating file
    debug: 
      msg: "Please create {{ filename }}"
