---
- name: Deploying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Creating file and setting immutable attribute
    debug: 
      msg: "Please create {{ filename }} and set immutable attribute"
  - name: Remove the file
    file:
      path: "{{ filename }}"
      state: absent
