---
- name: Deploying test environment
  hosts: all
  become: True
  gather_facts: True
  gather_subset: ['!all','!min','os_family']
  vars_files:
  - vars.yml
  tasks:
#  - debug: 
#      var: ansible_facts
#  - debug: 
#      msg: "Uninstalling the package '{{ package }}'"
  - name: "Uninstalling the package '{{ package }}'"
    apt:
      name: "{{ package }}"
      state: "absent"
    when: ansible_facts['os_family'] == "Debian"
  - name: "Giving sudo permissions for test user"
    template:
      src: "sudoers.j2"
      dest: "/etc/sudoers.d/{{ username }}"
      owner: "root"
      group: "root"
      mode: 0440
      validate: "/usr/sbin/visudo -cf %s"
