---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: True
  gather_subset:
  - "!all"
  - "!min"
  - "network"
  vars_files:
  - vars.yml
  tasks:
  - name: "Deleting the files"
    file:
      path: "{{ item }}"
      state: "absent"
    with_items:
    - "{{ filename }}"
#  - name: Print all available facts
#    ansible.builtin.debug:
#      var: ansible_facts
  - name: "Store default gateway into file"
    lineinfile:
      line: "{{ ansible_facts['default_ipv4']['gateway'] }}"
      path: "{{ filename }}" 
      create: True
