---
- name: Solving test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset: ['!all','!min','devices']
  vars_files:
  - vars.yml
  tasks:
#  - name: "Storing UUID in a file {{ filename }}"
#    debug:
#      msg: "{{ ansible_facts }}"
  - name: "Store string in a file {{ filename }}"
    lineinfile: 
      path: "{{ filename }}"
      line: "{{ ansible_facts['product_uuid'] }}"
      state: "present"
      create: True
