---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  vars:
  - destination_file: "{{ destination }}/{{ filename }}"
  tasks:
  - name: "Deleting a file {{ destination_file }}"
    file: 
      path: "{{ destination_file }}"
      state: "absent"
  - name: "Creating a symbolic link {{ destination_file }}"
    file: 
      src: "{{ source }}/{{ filename }}"
      dest: "{{ destination_file }}"
      state: "link"
