---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: True
  gather_subset: ['!all','!min','os_family']
  vars_files:
  - vars.yml
  tasks:
  - name: "Uninstalling {{ package }} package"
    apt:
      name: "{{ package }}"
      state: absent
    when: ansible_facts['os_family'] == "Debian"
