---
- name: Solving test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Create a file
    file: 
      path: "{{ filename }}"
      state: touch
