---
- name: Solving test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Creating a file {{ filename }} and setting immutable attribute"
    file: 
      path: "{{ filename }}"
      state: touch
      attributes: "+i"
    ignore_errors: True
