---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Deleting a file {{ workdir }}/{{ filename }}"
    file:
      path: "{{ workdir }}/{{ filename }}"
      state: "absent"
#  - name: Install necessary packages
#    package:
#      name: unzip
#      state: present
  - name: Unarchive a file that is already on the remote machine
    unarchive:
      src: "{{ workdir }}/{{ archive }}"
      dest: "{{ workdir }}"
      remote_src: yes
      extra_opts:
      - "usr/share/man/man1/{{ filename }}"
      - --strip-components=4
