---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Deleting a file {{ destination }}/{{ filename }}"
    file: 
      path: "{{ destination }}/{{ filename }}"
      state: "absent"
  - name: "Creating a symbolic link {{ destination }}/{{ filename }}"
    file: 
      src: "{{ source }}/{{ filename }}"
      dest: "{{ destination }}/{{ filename }}"
      state: link
