---
- name: Solving test environment
  hosts: all
  become: True
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Deleting a file {{ filename }}"
    file: 
      path: "{{ filename }}"
      state: "absent"
  - name: "Creating a named pipe: {{ filename }}"
    shell: "mkfifo {{ filename }}"
