---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      var: p
  - debug:
      msg: "File {{ filename }} exists"
    when: p.stat.exists is defined and p.stat.exists == True
  - fail:
      msg: "File does NOT exist"
    when: p.stat.exists is not defined or p.stat.exists == False
  - debug:
      msg: "File {{ filename }} is regular file"
    when: p.stat.isreg is defined and p.stat.isreg == True
  - fail:
      msg: "File is NOT a regular file"
    when: p.stat.isreg is not defined or p.stat.isreg == False
  - debug:
      msg: "File {{ filename }} has execute permission for an user"
    when: p.stat.xusr is defined and p.stat.xusr == True
  - fail:
      msg: "File does NOT have execute permission for an user"
    when: p.stat.xusr is not defined or p.stat.xusr == False
  - debug:
      msg: "File {{ filename }} has execute permission for a group"
    when: p.stat.xgrp is defined and p.stat.xgrp == True
  - fail:
      msg: "File does NOT have execute permission for a group"
    when: p.stat.xgrp is not defined or p.stat.xgrp == False
  - debug:
      msg: "File {{ filename }} has execute permission for others"
    when: p.stat.xoth is defined and p.stat.xoth == True
  - fail:
      msg: "File does NOT have execute permission for others"
    when: p.stat.xoth is not defined or p.stat.xoth == False
