---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset: ['!all','!min','devices']
  vars_files:
  - vars.yml
  tasks:
  - name: Stat filename
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      msg: "Path {{ p.stat.path }} exists"
    when: p.stat.exists is defined and p.stat.exists == True
  - debug:
      msg: "Mime type {{ p.stat.mimetype }}"
    when: p.stat.mimetype is defined
  - fail:
      msg: "Path {{ filename }} does NOT exist or NOT a filename or NOT executable"
    when: p.stat.isreg is not defined or p.stat.isreg == False or p.stat.mimetype != "application/x-sharedlib"
