---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset:
  - "!all"
  - "!min"
  - "network"
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: f
  - debug:
      msg: "Path {{ f.stat.path }} exists"
    when: f.stat.exists is defined and f.stat.exists == True
  - fail:
      msg: "Path does NOT exist or NOT a regular file"
    when: f.stat.exists is not defined or f.stat.exists == False
  - name: Check if line is present in the file
    lineinfile:
      path: "{{ filename }}"
#      regex: "(\\s+{{ ansible_facts['default_ipv4']['gateway'] }}\\s+)"
      regex: "{{ ansible_facts['default_ipv4']['gateway'] }}"
      line: "{{ ansible_facts['default_ipv4']['gateway'] }}"
#      backrefs: yes
    check_mode: True
    register: c
    failed_when: (c is changed) or (c is failed)
