---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: f
  - name: "Stat hard link {{ hardlink }}"
    stat:
      path: "{{ hardlink }}"
    register: h
  - debug:
      msg: "Path {{ f.stat.path }} exists"
    when: f.stat.exists is defined and f.stat.exists == True
  - debug:
      msg: "Path {{ h.stat.path }} exists"
    when: h.stat.exists is defined and h.stat.exists == True
  - debug:
      msg: "File inode # {{ f.stat.inode }} not equal to hard link inode # {{ h.stat.inode }}"
    when: f.stat.inode is defined and h.stat.inode is defined and f.stat.inode != h.stat.inode
  - fail:
      msg: "Files do not exist or are not linking to the same inode"
    when: f.stat.exists not defined
  - name: Check if line is present in the file
    lineinfile:
      path: "{{ filename }}"
      regex: "{{ f.stat.inode }}"
      line: "{{ f.stat.inode }}"
    check_mode: True
    register: c
    failed_when: (c is changed) or (c is failed)
