---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      var: p
  - debug:
      msg: "File {{ filename }} exists"
    when: p.stat.exists is defined and p.stat.exists == True
  - fail:
      msg: "File does NOT exist"
    when: p.stat.exists is not defined or p.stat.exists == False
  - debug:
      msg: "File {{ filename }} is regular file"
    when: p.stat.isreg is defined and p.stat.isreg == True
  - fail:
      msg: "File is NOT a regular file"
    when: p.stat.isreg is not defined or p.stat.isreg == False
  - debug:
      msg: "File {{ filename }} has write permission for an user"
    when: p.stat.wusr is defined and p.stat.wusr == True
  - fail:
      msg: "File does NOT have write permission for an user"
    when: p.stat.wusr is not defined or p.stat.wusr == False
  - debug:
      msg: "File {{ filename }} has write permission for a group"
    when: p.stat.wgrp is defined and p.stat.wgrp == True
  - fail:
      msg: "File does NOT have write permission for a group"
    when: p.stat.wgrp is not defined or p.stat.wgrp == False
  - debug:
      msg: "File {{ filename }} has write permission for others"
    when: p.stat.woth is defined and p.stat.woth == True
  - fail:
      msg: "File does NOT have write permission for others"
    when: p.stat.woth is not defined or p.stat.woth == False
