---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: Stat filename
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      var: p.stat.attributes
  - debug:
      msg: "Path exists and is a filename and has immutable attribute"
    when: p.stat.isreg is defined and p.stat.isreg and "immutable" in p.stat.attributes
  - fail:
      msg: "Path does NOT exist or NOT a filename or has NO immutable attribute"
    when: p.stat.isreg is not defined or p.stat.isreg == False or "immutable" not in p.stat.attributes

