---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat directory{{ directory }}"
    stat:
      path: "{{ directory }}"
    register: p
  - debug:
      msg: "Path {{ p.stat.path }} exists"
    when: p.stat.exists is defined and p.stat.exists == True
  - debug:
      msg: "Mime type {{ p.stat.mimetype }}"
    when: p.stat.mimetype is defined
  - fail:
      msg: "Path does NOT exist or NOT a directory"
    when: p.stat.isdir is not defined or p.stat.isdir == False
