---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ workdir }}/{{ filename }}"
    stat:
      path: "{{ workdir }}/{{ filename }}"
    register: p
  - debug:
      var: p
  - fail:
      msg: "Path {{ p.stat.path }} does NOT exist"
    when: p.stat.exists is not defined or p.stat.exists != True
  - fail:
      msg: "Path does NOT exist or NOT a filename"
    when: p.stat.isreg is not defined or p.stat.isreg == False
  - fail:
      msg: "Mime type mismatch {{ p.stat.mimetype }} expected application/gzip"
    when: p.stat.mimetype != "application/gzip"
  - fail:
      msg: "Wrong file size {{ p.stat.size }} expected 13332"
    when: p.stat.size != 13332

