---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: False
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat filename {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      var: p
  - debug:
      msg: "File {{ filename }} exists"
    when: p.stat.exists is defined and p.stat.exists == True
  - fail:
      msg: "File does NOT exist"
    when: p.stat.exists is not defined or p.stat.exists == False
  - debug:
      msg: "File {{ filename }} is regular file"
    when: p.stat.isreg is defined and p.stat.isreg == True
  - fail:
      msg: "File is NOT a regular file"
    when: p.stat.isreg is not defined or p.stat.isreg == False
  - debug:
      msg: "File {{ filename }} has read permission for an user"
    when: p.stat.rusr is defined and p.stat.rusr == True
  - fail:
      msg: "File does NOT have read permission for an user"
    when: p.stat.rusr is defined and p.stat.rusr == False
  - debug:
      msg: "File {{ filename }} has NO read permission for a group"
    when: p.stat.rgrp is defined and p.stat.rgrp == False
  - fail:
      msg: "File has read permission for a group"
    when: p.stat.rgrp is defined and p.stat.rgrp == True
  - debug:
      msg: "File {{ filename }} has NO read permission for others"
    when: p.stat.roth is defined and p.stat.roth == False
  - fail:
      msg: "File has write permission for others"
    when: p.stat.roth is defined and p.stat.roth == True
