---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset: ['!all','!min','devices']
  vars_files:
  - vars.yml
  tasks:
  - name: "Stat file {{ filename }}"
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      msg: "Path {{ filename }} exists and is a filename"
    when: p.stat.isreg is defined and p.stat.isreg
  - fail:
      msg: "Path {{ filename }} exists and is a filename"
    when: p.stat.isreg is defined and p.stat.isreg == True
