---
- name: Verifying test environment
  hosts: all
  become: False
  gather_facts: True
  gather_subset: ['!all','!min','devices']
  vars_files:
  - vars.yml
  tasks:
  - name: Stat filename
    stat:
      path: "{{ filename }}"
    register: p
  - debug:
      msg: "Path exists and is a filename"
    when: p.stat.isreg is defined and p.stat.isreg
  - fail:
      msg: "Path does NOT exist or NOT a filename"
    when: p.stat.isreg is not defined or p.stat.isreg == False
  - name: Match string in a file in check mode
    lineinfile:
      path: "{{ filename }}"
      line: "{{ ansible_facts['product_uuid'] }}"
      state: present
    check_mode: yes
    register: r
  - fail:
      msg: "Line is absent in the filename"
    when: r.changed == True
